[package]
name = "dot15d4"
version = "0.1.2"
edition = "2021"
repository = "https://github.com/thvdveld/dot15d4"
description = "IEEE 802.15.4 implementation in Rust"
license = "MIT OR Apache-2.0"
categories = ["embedded", "network-programming", "no-std"]
keywords = ["ieee802154", "WPAN", "smoltcp"]

[dependencies]
dot15d4-frame3 = { version = "0.0.1", path = "../dot15d4-frame3" }
mpmc_channel = { version = "0.0.1", path = "../mpmc_channel" }
static_cell = "2.1"

bitmaps = { version = "3.2", default-features = false }
typenum = "1.18"
generic-array = "1.2"

log = { version = "0.4.21", optional = true }
defmt = { version = "0.3", optional = true }

critical-section = "1.1"
rand_core = { version = "0.6.4", default-features = false }
embedded-hal-async = { version = "1.0.0" }
heapless = { version = "0.8.0" }

arbitrary = { version = "1.3.2", features = ["derive"], optional = true }

rtos-trace = { git = "https://github.com/fg-cfh/rtos-trace", optional = true }

[dev-dependencies]
critical-section = { version = "1.1", features = ["std"] }
pollster = { version = "0.3", features = ["macro"] }
rand = "0.8.5"

[features]
## Enable std only features
std = ["log"]
default = ["std"]

## Use tracing for logging
log = ["dep:log"]
## Use defmt for logging
defmt = ["dep:defmt"]

## Enable fuzzing
fuzz = ["dep:arbitrary"]

# Support for information elements
ies = []

rtos-trace = ["dep:rtos-trace"]
